    plt.figure(figsize=(10, 6))
    plt.plot(edge_range, timevalueslist, label='List Implementation', marker='o')
    plt.plot(edge_range, timevaluesmatrix, label='Matrix Implementation', marker='x')
    plt.xlabel('Number of Edges')
    plt.ylabel('Time Taken (seconds)')
    plt.title('Dijkstra Algorithm Performance')
    plt.grid(True)
    plt.legend()
    plt.show()